# Generated by Django 5.0.6 on 2024-05-15 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='likes',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
